# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bb_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='user_quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes_of_user', to='login_reg_app.User'),
        ),
    ]
