# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0001_initial'),
        ('bb_app', '0002_auto_20161123_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0, null=True)),
                ('total_pokes', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pokee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_poked', to='login_reg_app.User')),
                ('poker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_poker', to='login_reg_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='quote',
            name='all_users',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='user_quote',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
