# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
